### ISSUE TITLE
조나단 import & 믹사모 연결

### ISSUE THREAD

**Issue by ghost** [Gongju-Unity-Bootcamp/SchneeIM#2]

**Comment by ghost** [comment]
1. 민수 에셋 import
2. 민수에게 필요한 믹사모: Getting up - Ducking - Praying - Crouch To Stand - Brutal to happy walking

**Comment by ghost** [comment]
민수 에셋 import 완료! 조나단으로 이름 변경했으니 조나단이라고 부르겠습니다.

**Comment by kimxesxie** [comment]
완료
