### ISSUE TITLE
씬에 필요한 애니메이션 작업

### ISSUE THREAD

**Issue by ghost** [Gongju-Unity-Bootcamp/SchneeIM#4]

**Comment by kimxesxie** [comment]
1. 아비누스 statue 뒷부분에 light effect(근엄하게 반짝거리는) 구현: statue 옆으로 옮겨지기 전에 한 번 반짝거려주기
2. 아비누스 statue가 옆으로 옮겨지는 애니메이션 구현

**Comment by ghost** [comment]
박혜린이 작업 완료 - 김혜신이 검수 후 수정함.
